namespace TownOfUs
{
    public enum RoleEnum
    {
        Sheriff,
        Jester,
        Engineer,
        Mayor,
        Swapper,
        Investigator,
        Medic,
        Seer,
        Executioner,
        Lawyer,
        TimeLord,
        Spy,
        Glitch,
        Snitch,
        Arsonist,
        Altruist,
        Phantom,
        Vigilante,
        Haunter,
        Veteran,
        Amnesiac,
        Juggernaut,
        Tracker,
        Transporter,
        Medium,
        Trapper,
        Survivor,
        GuardianAngel,
        Mystic,
        Plaguebearer,
        Pestilence,
        Werewolf,
        Detective,
        Imitator,
        Doomsayer,
        Vampire,
        Prosecutor,
        Oracle,
        Aurial,
        Hunter,
        Politician,
        Warden,
        Jailor,
        SoulCollector,
        Stalker,

        Miner,
        Swooper,
        Morphling,
        Janitor,
        Undertaker,
        Grenadier,
        Traitor,
        Blackmailer,
        Escapist,
        Bomber,
        Detonator,
        Warlock,
        Venerer,
        Hypnotist,
        Disorienter,

        Crewmate,
        Impostor,

        None
    }

    public enum ModifierEnum
    {
        Lover,
        Torch,
        Diseased,
        Flash,
        Tiebreaker,
        Giant,
        Mini,
        UpsideDown,
        Radiative,
        TomFoolery,
        ButtonBarry,
        Bait,
        Freeze,
        Sleuth,
        Aftermath,
        Radar,
        Disperser,
        Multitasker,
        DoubleShot,
        Underdog,
        Frosty,
        SixthSense,
        Shy
    }

    public enum AbilityEnum
    {
        Assassin
    }
}
